#!/usr/bin/env python

env = SConscript("C:\DISORDER\pgm\Godot_v3.5.2-stable_mono_win64\godot-cpp\SConstruct")

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=['src/'])
sources = Glob('src/*.cpp')

library = env.SharedLibrary(
    "bin/test.{}.{}.{}{}".format(
        env["platform"], env["target"], env["arch_suffix"], env["SHLIBSUFFIX"]
    ),
    source=sources,
)

Default(library)
